-- Base de datos para sistema de gestión de mesas (Supabase/PostgreSQL)

-- Eliminar tabla si existe para empezar limpio
DROP TABLE IF EXISTS mesas CASCADE;

-- Tabla de mesas
CREATE TABLE mesas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_mesa INTEGER NOT NULL UNIQUE,
    capacidad INTEGER NOT NULL CHECK (capacidad > 0),
    estado TEXT DEFAULT 'disponible' CHECK (estado IN ('disponible', 'ocupada', 'reservada', 'mantenimiento')),
    cliente_nombre TEXT NULL,
    cliente_cantidad INTEGER NULL,
    hora_entrada TEXT NULL,
    hora_salida TEXT NULL,
    fecha_reserva DATE NULL,
    ubicacion TEXT NULL,
    observaciones TEXT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Trigger para actualizar updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_mesas_updated_at 
    BEFORE UPDATE ON mesas 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();

-- Insertar mesas de ejemplo
INSERT INTO mesas (numero_mesa, capacidad, estado, ubicacion) VALUES
(1, 4, 'disponible', 'Sala principal'),
(2, 2, 'disponible', 'Terraza'),
(3, 6, 'disponible', 'Sala principal'),
(4, 4, 'disponible', 'Sala principal'),
(5, 2, 'disponible', 'Terraza'),
(6, 8, 'disponible', 'Sala VIP'),
(7, 4, 'disponible', 'Sala principal'),
(8, 3, 'disponible', 'Terraza'),
(9, 4, 'disponible', 'Sala principal');

-- Habilitar RLS (Row Level Security)
ALTER TABLE mesas ENABLE ROW LEVEL SECURITY;

-- Eliminar políticas existentes si las hay
DROP POLICY IF EXISTS "Allow all operations on mesas" ON mesas;

-- Política para permitir todas las operaciones (para desarrollo)
CREATE POLICY "Allow all operations on mesas" ON mesas
    FOR ALL USING (true) WITH CHECK (true);
